/** Metadata van één provider in de catalogus — alleen UI, niet gedeeld met companion. */
export interface ProviderCatalogEntry {
  id: string;
  name: string;
  tier: "free" | "paid" | "local" | "custom";
  badge: string;
  tagline: string;
  freeLimit?: string;
  quality: number;
  speed: number;
  signupUrl: string;
  keyPlaceholder: string;
  requiresKey: boolean;
  supportsModel: boolean;
  supportsBaseUrl: boolean;
  supportsPrimary: boolean;
  defaultModel: string;
  defaultBaseUrl?: string;
}

/**
 * Volledige provider-catalogus. Voeg hier nieuwe providers toe — de UI pikt ze
 * automatisch op bij de volgende update. Volgorde = volgorde in het instellingen-paneel.
 * "primary" = mag als sterkste model EERST gebruikt worden (tier -1 in de pool).
 */
export const PROVIDER_CATALOG: ProviderCatalogEntry[] = [
  {
    id: "groq",
    name: "Groq",
    tier: "free",
    badge: "GRATIS",
    tagline: "Llama-3.3-70B op AI-chip — razendsnel en gratis",
    freeLimit: "14.400 verz/dag",
    quality: 4,
    speed: 5,
    signupUrl: "https://console.groq.com",
    keyPlaceholder: "gsk_…",
    requiresKey: true,
    supportsModel: true,
    supportsBaseUrl: false,
    supportsPrimary: true,
    defaultModel: "llama-3.3-70b-versatile",
  },
  {
    id: "cerebras",
    name: "Cerebras",
    tier: "free",
    badge: "GRATIS",
    tagline: "Eigen CS2-chip — snelste token-output beschikbaar",
    freeLimit: "60 verz/min",
    quality: 4,
    speed: 5,
    signupUrl: "https://cloud.cerebras.ai",
    keyPlaceholder: "csk_…",
    requiresKey: true,
    supportsModel: true,
    supportsBaseUrl: false,
    supportsPrimary: true,
    defaultModel: "llama3.1-8b",
  },
  {
    id: "gemini",
    name: "Gemini (sleutel 1)",
    tier: "free",
    badge: "GRATIS/BETAALD",
    tagline: "Google Gemini — gratis tier of je eigen betaalde sleutel",
    freeLimit: "1.500 verz/dag gratis",
    quality: 4,
    speed: 4,
    signupUrl: "https://aistudio.google.com/apikey",
    keyPlaceholder: "AIza…",
    requiresKey: true,
    supportsModel: true,
    supportsBaseUrl: false,
    supportsPrimary: true,
    defaultModel: "gemini-2.0-flash",
  },
  {
    id: "gemini2",
    name: "Gemini (sleutel 2)",
    tier: "free",
    badge: "GRATIS/BETAALD",
    tagline: "Tweede Gemini-sleutel — automatisch wissel bij limiet",
    freeLimit: "+1.500 verz/dag",
    quality: 4,
    speed: 4,
    signupUrl: "https://aistudio.google.com/apikey",
    keyPlaceholder: "AIza…",
    requiresKey: true,
    supportsModel: true,
    supportsBaseUrl: false,
    supportsPrimary: true,
    defaultModel: "gemini-2.0-flash",
  },
  {
    id: "gemini3",
    name: "Gemini (sleutel 3)",
    tier: "free",
    badge: "GRATIS/BETAALD",
    tagline: "Derde Gemini-sleutel — Google Cloud project met gratis dagquota",
    freeLimit: "+1.500 verz/dag",
    quality: 4,
    speed: 4,
    signupUrl: "https://console.cloud.google.com/apis/credentials",
    keyPlaceholder: "AIza…",
    requiresKey: true,
    supportsModel: false,
    supportsBaseUrl: false,
    supportsPrimary: true,
    defaultModel: "gemini-2.0-flash",
  },
  {
    id: "gemini4",
    name: "Gemini (sleutel 4)",
    tier: "free",
    badge: "GRATIS/BETAALD",
    tagline: "Vierde Gemini-sleutel — extra dagquota als 3 uitgeput is",
    freeLimit: "+1.500 verz/dag",
    quality: 4,
    speed: 4,
    signupUrl: "https://console.cloud.google.com/apis/credentials",
    keyPlaceholder: "AIza…",
    requiresKey: true,
    supportsModel: false,
    supportsBaseUrl: false,
    supportsPrimary: true,
    defaultModel: "gemini-2.0-flash",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    tier: "free",
    badge: "GRATIS/BETAALD",
    tagline: "Eén sleutel, honderden modellen — gratis én betaalde toppers",
    freeLimit: "Per model verschilt",
    quality: 4,
    speed: 3,
    signupUrl: "https://openrouter.ai/keys",
    keyPlaceholder: "sk-or-v1-…",
    requiresKey: true,
    supportsModel: true,
    supportsBaseUrl: false,
    supportsPrimary: true,
    defaultModel: "meta-llama/llama-3.3-70b-instruct:free",
  },
  {
    id: "github",
    name: "GitHub Models",
    tier: "free",
    badge: "GRATIS",
    tagline: "GPT-4o-mini voor elke GitHub-gebruiker — geen betaalkaart nodig",
    freeLimit: "Inbegrepen in GitHub",
    quality: 4,
    speed: 3,
    signupUrl: "https://github.com/settings/tokens",
    keyPlaceholder: "ghp_…",
    requiresKey: true,
    supportsModel: true,
    supportsBaseUrl: false,
    supportsPrimary: true,
    defaultModel: "openai/gpt-4o-mini",
  },
  {
    id: "together",
    name: "Together AI",
    tier: "free",
    badge: "GRATIS+",
    tagline: "Populair bij AI-developers — gratis credits, betaalbaar opschalen",
    freeLimit: "Startcredits gratis",
    quality: 4,
    speed: 4,
    signupUrl: "https://api.together.ai",
    keyPlaceholder: "…",
    requiresKey: true,
    supportsModel: true,
    supportsBaseUrl: false,
    supportsPrimary: true,
    defaultModel: "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo",
  },
  {
    id: "mistral",
    name: "Mistral AI",
    tier: "free",
    badge: "GRATIS",
    tagline: "Europees bedrijf — Mistral Nemo licht, snel en meertalig",
    freeLimit: "Gratis tier beschikbaar",
    quality: 3,
    speed: 4,
    signupUrl: "https://console.mistral.ai",
    keyPlaceholder: "…",
    requiresKey: true,
    supportsModel: true,
    supportsBaseUrl: false,
    supportsPrimary: true,
    defaultModel: "open-mistral-nemo",
  },
  {
    id: "hyperbolic",
    name: "Hyperbolic",
    tier: "free",
    badge: "GRATIS+",
    tagline: "GPU-cloud — razendsnel bij zwaardere modellen",
    freeLimit: "$10 startcredits",
    quality: 4,
    speed: 5,
    signupUrl: "https://app.hyperbolic.xyz",
    keyPlaceholder: "…",
    requiresKey: true,
    supportsModel: true,
    supportsBaseUrl: false,
    supportsPrimary: true,
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct",
  },
  {
    id: "paid",
    name: "Betaalde topsleutel",
    tier: "paid",
    badge: "BETAALD",
    tagline: "Sterkste kwaliteit — Claude, GPT-4o of elk topmodel via OpenRouter",
    quality: 5,
    speed: 3,
    signupUrl: "https://openrouter.ai/keys",
    keyPlaceholder: "sk-or-v1-…",
    requiresKey: true,
    supportsModel: true,
    supportsBaseUrl: true,
    supportsPrimary: true,
    defaultModel: "anthropic/claude-3.5-sonnet",
    defaultBaseUrl: "https://openrouter.ai/api/v1",
  },
  {
    id: "custom",
    name: "Eigen / andere provider",
    tier: "custom",
    badge: "EIGEN",
    tagline: "Elke OpenAI-compatibele API — plak je eigen URL, sleutel en model",
    quality: 4,
    speed: 3,
    signupUrl: "https://platform.openai.com/docs/api-reference",
    keyPlaceholder: "API-sleutel van je provider",
    requiresKey: true,
    supportsModel: true,
    supportsBaseUrl: true,
    supportsPrimary: true,
    defaultModel: "gpt-4o-mini",
    defaultBaseUrl: "https://api.openai.com/v1",
  },
  {
    id: "ollama",
    name: "Ollama (eigen server)",
    tier: "local",
    badge: "LOKAAL",
    tagline: "Eigen model op je machine of server via SSH-tunnel — 100% privé",
    quality: 4,
    speed: 3,
    signupUrl: "https://ollama.ai",
    keyPlaceholder: "ollama",
    requiresKey: false,
    supportsModel: true,
    supportsBaseUrl: true,
    supportsPrimary: true,
    defaultModel: "qwen2.5:32b",
    defaultBaseUrl: "http://localhost:11434/v1",
  },
];
