/** Tweetalige tekst (Nederlands + Engels). De UI kiest op basis van de taalkeuze. */
export interface Loc {
  nl: string;
  en: string;
}

/** Metadata van één provider in de catalogus — alleen UI, niet gedeeld met companion. */
export interface ProviderCatalogEntry {
  id: string;
  tier: "free" | "paid" | "local" | "custom";
  name: Loc;
  badge: Loc;
  tagline: Loc;
  freeLimit?: Loc;
  quality: number;
  speed: number;
  signupUrl: string;
  keyPlaceholder: Loc;
  requiresKey: boolean;
  supportsModel: boolean;
  supportsBaseUrl: boolean;
  supportsPrimary: boolean;
  defaultModel: string;
  defaultBaseUrl?: string;
}

/**
 * Volledige provider-catalogus. Voeg hier nieuwe providers toe — de UI pikt ze
 * automatisch op bij de volgende update. Volgorde = volgorde in het instellingen-paneel.
 * "primary" = mag als sterkste model EERST gebruikt worden (tier -1 in de pool).
 * Alle zichtbare tekst is tweetalig zodat de Engelse modus ook echt Engels is.
 */
export const PROVIDER_CATALOG: ProviderCatalogEntry[] = [
  {
    id: "groq",
    tier: "free",
    name: { nl: "Groq", en: "Groq" },
    badge: { nl: "GRATIS", en: "FREE" },
    tagline: { nl: "Llama-3.3-70B op AI-chip, razendsnel en gratis", en: "Llama-3.3-70B on an AI chip, blazing fast and free" },
    freeLimit: { nl: "14.400 verz/dag", en: "14,400 req/day" },
    quality: 4,
    speed: 5,
    signupUrl: "https://console.groq.com",
    keyPlaceholder: { nl: "gsk_…", en: "gsk_…" },
    requiresKey: true,
    supportsModel: true,
    supportsBaseUrl: false,
    supportsPrimary: true,
    defaultModel: "llama-3.3-70b-versatile",
  },
  {
    id: "cerebras",
    tier: "free",
    name: { nl: "Cerebras", en: "Cerebras" },
    badge: { nl: "GRATIS", en: "FREE" },
    tagline: { nl: "Eigen CS2-chip, snelste token-output beschikbaar", en: "In-house CS2 chip, the fastest token output available" },
    freeLimit: { nl: "60 verz/min", en: "60 req/min" },
    quality: 4,
    speed: 5,
    signupUrl: "https://cloud.cerebras.ai",
    keyPlaceholder: { nl: "csk_…", en: "csk_…" },
    requiresKey: true,
    supportsModel: true,
    supportsBaseUrl: false,
    supportsPrimary: true,
    defaultModel: "llama3.1-8b",
  },
  {
    id: "gemini",
    tier: "free",
    name: { nl: "Gemini (sleutel 1)", en: "Gemini (key 1)" },
    badge: { nl: "GRATIS/BETAALD", en: "FREE/PAID" },
    tagline: { nl: "Google Gemini, gratis tier of je eigen betaalde sleutel", en: "Google Gemini, free tier or your own paid key" },
    freeLimit: { nl: "1.500 verz/dag gratis", en: "1,500 req/day free" },
    quality: 4,
    speed: 4,
    signupUrl: "https://aistudio.google.com/apikey",
    keyPlaceholder: { nl: "AIza…", en: "AIza…" },
    requiresKey: true,
    supportsModel: true,
    supportsBaseUrl: false,
    supportsPrimary: true,
    defaultModel: "gemini-2.0-flash",
  },
  {
    id: "gemini2",
    tier: "free",
    name: { nl: "Gemini (sleutel 2)", en: "Gemini (key 2)" },
    badge: { nl: "GRATIS/BETAALD", en: "FREE/PAID" },
    tagline: { nl: "Tweede Gemini-sleutel, automatisch wissel bij limiet", en: "Second Gemini key, switches automatically at the limit" },
    freeLimit: { nl: "+1.500 verz/dag", en: "+1,500 req/day" },
    quality: 4,
    speed: 4,
    signupUrl: "https://aistudio.google.com/apikey",
    keyPlaceholder: { nl: "AIza…", en: "AIza…" },
    requiresKey: true,
    supportsModel: true,
    supportsBaseUrl: false,
    supportsPrimary: true,
    defaultModel: "gemini-2.0-flash",
  },
  {
    id: "gemini3",
    tier: "free",
    name: { nl: "Gemini (sleutel 3)", en: "Gemini (key 3)" },
    badge: { nl: "GRATIS/BETAALD", en: "FREE/PAID" },
    tagline: { nl: "Derde Gemini-sleutel, Google Cloud project met gratis dagquota", en: "Third Gemini key, a Google Cloud project with a free daily quota" },
    freeLimit: { nl: "+1.500 verz/dag", en: "+1,500 req/day" },
    quality: 4,
    speed: 4,
    signupUrl: "https://console.cloud.google.com/apis/credentials",
    keyPlaceholder: { nl: "AIza…", en: "AIza…" },
    requiresKey: true,
    supportsModel: false,
    supportsBaseUrl: false,
    supportsPrimary: true,
    defaultModel: "gemini-2.0-flash",
  },
  {
    id: "gemini4",
    tier: "free",
    name: { nl: "Gemini (sleutel 4)", en: "Gemini (key 4)" },
    badge: { nl: "GRATIS/BETAALD", en: "FREE/PAID" },
    tagline: { nl: "Vierde Gemini-sleutel, extra dagquota als 3 uitgeput is", en: "Fourth Gemini key, extra daily quota when 3 runs out" },
    freeLimit: { nl: "+1.500 verz/dag", en: "+1,500 req/day" },
    quality: 4,
    speed: 4,
    signupUrl: "https://console.cloud.google.com/apis/credentials",
    keyPlaceholder: { nl: "AIza…", en: "AIza…" },
    requiresKey: true,
    supportsModel: false,
    supportsBaseUrl: false,
    supportsPrimary: true,
    defaultModel: "gemini-2.0-flash",
  },
  {
    id: "openrouter",
    tier: "free",
    name: { nl: "OpenRouter", en: "OpenRouter" },
    badge: { nl: "GRATIS/BETAALD", en: "FREE/PAID" },
    tagline: { nl: "Eén sleutel, honderden modellen, gratis en betaalde toppers", en: "One key, hundreds of models, free and paid flagships" },
    freeLimit: { nl: "Per model verschilt", en: "Varies per model" },
    quality: 4,
    speed: 3,
    signupUrl: "https://openrouter.ai/keys",
    keyPlaceholder: { nl: "sk-or-v1-…", en: "sk-or-v1-…" },
    requiresKey: true,
    supportsModel: true,
    supportsBaseUrl: false,
    supportsPrimary: true,
    defaultModel: "meta-llama/llama-3.3-70b-instruct:free",
  },
  {
    id: "github",
    tier: "free",
    name: { nl: "GitHub Models", en: "GitHub Models" },
    badge: { nl: "GRATIS", en: "FREE" },
    tagline: { nl: "GPT-4o-mini voor elke GitHub-gebruiker, geen betaalkaart nodig", en: "GPT-4o-mini for every GitHub user, no payment card needed" },
    freeLimit: { nl: "Inbegrepen in GitHub", en: "Included with GitHub" },
    quality: 4,
    speed: 3,
    signupUrl: "https://github.com/settings/tokens",
    keyPlaceholder: { nl: "ghp_…", en: "ghp_…" },
    requiresKey: true,
    supportsModel: true,
    supportsBaseUrl: false,
    supportsPrimary: true,
    defaultModel: "openai/gpt-4o-mini",
  },
  {
    id: "together",
    tier: "free",
    name: { nl: "Together AI", en: "Together AI" },
    badge: { nl: "GRATIS+", en: "FREE+" },
    tagline: { nl: "Populair bij AI-developers, gratis credits, betaalbaar opschalen", en: "Popular with AI developers, free credits, affordable to scale" },
    freeLimit: { nl: "Startcredits gratis", en: "Free starter credits" },
    quality: 4,
    speed: 4,
    signupUrl: "https://api.together.ai",
    keyPlaceholder: { nl: "…", en: "…" },
    requiresKey: true,
    supportsModel: true,
    supportsBaseUrl: false,
    supportsPrimary: true,
    defaultModel: "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo",
  },
  {
    id: "mistral",
    tier: "free",
    name: { nl: "Mistral AI", en: "Mistral AI" },
    badge: { nl: "GRATIS", en: "FREE" },
    tagline: { nl: "Europees bedrijf, Mistral Nemo licht, snel en meertalig", en: "European company, Mistral Nemo is light, fast and multilingual" },
    freeLimit: { nl: "Gratis tier beschikbaar", en: "Free tier available" },
    quality: 3,
    speed: 4,
    signupUrl: "https://console.mistral.ai",
    keyPlaceholder: { nl: "…", en: "…" },
    requiresKey: true,
    supportsModel: true,
    supportsBaseUrl: false,
    supportsPrimary: true,
    defaultModel: "open-mistral-nemo",
  },
  {
    id: "hyperbolic",
    tier: "free",
    name: { nl: "Hyperbolic", en: "Hyperbolic" },
    badge: { nl: "GRATIS+", en: "FREE+" },
    tagline: { nl: "GPU-cloud, razendsnel bij zwaardere modellen", en: "GPU cloud, blazing fast on heavier models" },
    freeLimit: { nl: "$10 startcredits", en: "$10 starter credits" },
    quality: 4,
    speed: 5,
    signupUrl: "https://app.hyperbolic.xyz",
    keyPlaceholder: { nl: "…", en: "…" },
    requiresKey: true,
    supportsModel: true,
    supportsBaseUrl: false,
    supportsPrimary: true,
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct",
  },
  {
    id: "paid",
    tier: "paid",
    name: { nl: "Betaalde topsleutel", en: "Paid top key" },
    badge: { nl: "BETAALD", en: "PAID" },
    tagline: { nl: "Sterkste kwaliteit, Claude, GPT-4o of elk topmodel via OpenRouter", en: "Strongest quality, Claude, GPT-4o or any top model via OpenRouter" },
    quality: 5,
    speed: 3,
    signupUrl: "https://openrouter.ai/keys",
    keyPlaceholder: { nl: "sk-or-v1-…", en: "sk-or-v1-…" },
    requiresKey: true,
    supportsModel: true,
    supportsBaseUrl: true,
    supportsPrimary: true,
    defaultModel: "anthropic/claude-3.5-sonnet",
    defaultBaseUrl: "https://openrouter.ai/api/v1",
  },
  {
    id: "custom",
    tier: "custom",
    name: { nl: "Eigen / andere provider", en: "Custom / other provider" },
    badge: { nl: "EIGEN", en: "CUSTOM" },
    tagline: { nl: "Elke OpenAI-compatibele API, plak je eigen URL, sleutel en model", en: "Any OpenAI-compatible API, paste your own URL, key and model" },
    quality: 4,
    speed: 3,
    signupUrl: "https://platform.openai.com/docs/api-reference",
    keyPlaceholder: { nl: "API-sleutel van je provider", en: "Your provider's API key" },
    requiresKey: true,
    supportsModel: true,
    supportsBaseUrl: true,
    supportsPrimary: true,
    defaultModel: "gpt-4o-mini",
    defaultBaseUrl: "https://api.openai.com/v1",
  },
  {
    id: "ollama",
    tier: "local",
    name: { nl: "Ollama (eigen server)", en: "Ollama (your own server)" },
    badge: { nl: "LOKAAL", en: "LOCAL" },
    tagline: { nl: "Eigen model op je machine of server via SSH-tunnel, 100% privé", en: "Your own model on your machine or server over an SSH tunnel, 100% private" },
    quality: 4,
    speed: 3,
    signupUrl: "https://ollama.ai",
    keyPlaceholder: { nl: "ollama", en: "ollama" },
    requiresKey: false,
    supportsModel: true,
    supportsBaseUrl: true,
    supportsPrimary: true,
    defaultModel: "qwen2.5:32b",
    defaultBaseUrl: "http://localhost:11434/v1",
  },
];
